import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainHeader from "@/components/ui/MainHeader";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "HarvestBridge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <head />
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center justify-center`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="container min-h-screen flex flex-col p-1">
              {/* Header container with responsive padding */}
              <header className="border sm:px-4  lg:px-4 py-2 w-full p-2 sm:p-4 flex flex-col gap-6 bg-background rounded-lg">
                <MainHeader />
              </header>

              {/* Main content container with responsive layout */}
              <section className="border flex-1 w-full px-2 sm:px-4 md:px-6 lg:px-8 mt-2 h-[calc(100vh-theme(spacing.24))] sm:h-[calc(100vh-theme(spacing.28))] overflow-auto rounded-lg">
                {children}
              </section>
            </main>
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
